[build]
builder = "NIXPACKS"
buildCommand = "pnpm run build"

[deploy]
startCommand = "pnpm start"
restartPolicyType = "ALWAYS"

providers = ["node", "python"]

[phases.setup]
nixPkgs = [
  "python3",
  "gnumake",
  "gcc",
  "libstdc++",
  "pkg-config"
]
